/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandOnboardingRouteImport } from './routes/brand.onboarding'
import { Route as BrandDashboardRouteImport } from './routes/brand.dashboard'
import { Route as AthleteOnboardingRouteImport } from './routes/athlete.onboarding'
import { Route as AthleteDashboardRouteImport } from './routes/athlete.dashboard'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandOnboardingRoute = BrandOnboardingRouteImport.update({
  id: '/brand/onboarding',
  path: '/brand/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandDashboardRoute = BrandDashboardRouteImport.update({
  id: '/brand/dashboard',
  path: '/brand/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteOnboardingRoute = AthleteOnboardingRouteImport.update({
  id: '/athlete/onboarding',
  path: '/athlete/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteDashboardRoute = AthleteDashboardRouteImport.update({
  id: '/athlete/dashboard',
  path: '/athlete/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/athlete/dashboard': typeof AthleteDashboardRoute
  '/athlete/onboarding': typeof AthleteOnboardingRoute
  '/brand/dashboard': typeof BrandDashboardRoute
  '/brand/onboarding': typeof BrandOnboardingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/athlete/dashboard': typeof AthleteDashboardRoute
  '/athlete/onboarding': typeof AthleteOnboardingRoute
  '/brand/dashboard': typeof BrandDashboardRoute
  '/brand/onboarding': typeof BrandOnboardingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/athlete/dashboard': typeof AthleteDashboardRoute
  '/athlete/onboarding': typeof AthleteOnboardingRoute
  '/brand/dashboard': typeof BrandDashboardRoute
  '/brand/onboarding': typeof BrandOnboardingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/admin/dashboard'
    | '/athlete/dashboard'
    | '/athlete/onboarding'
    | '/brand/dashboard'
    | '/brand/onboarding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/admin/dashboard'
    | '/athlete/dashboard'
    | '/athlete/onboarding'
    | '/brand/dashboard'
    | '/brand/onboarding'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/admin/dashboard'
    | '/athlete/dashboard'
    | '/athlete/onboarding'
    | '/brand/dashboard'
    | '/brand/onboarding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AthleteDashboardRoute: typeof AthleteDashboardRoute
  AthleteOnboardingRoute: typeof AthleteOnboardingRoute
  BrandDashboardRoute: typeof BrandDashboardRoute
  BrandOnboardingRoute: typeof BrandOnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/onboarding': {
      id: '/brand/onboarding'
      path: '/brand/onboarding'
      fullPath: '/brand/onboarding'
      preLoaderRoute: typeof BrandOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/dashboard': {
      id: '/brand/dashboard'
      path: '/brand/dashboard'
      fullPath: '/brand/dashboard'
      preLoaderRoute: typeof BrandDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/onboarding': {
      id: '/athlete/onboarding'
      path: '/athlete/onboarding'
      fullPath: '/athlete/onboarding'
      preLoaderRoute: typeof AthleteOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/dashboard': {
      id: '/athlete/dashboard'
      path: '/athlete/dashboard'
      fullPath: '/athlete/dashboard'
      preLoaderRoute: typeof AthleteDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AthleteDashboardRoute: AthleteDashboardRoute,
  AthleteOnboardingRoute: AthleteOnboardingRoute,
  BrandDashboardRoute: BrandDashboardRoute,
  BrandOnboardingRoute: BrandOnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
