/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesIdRouteImport } from './routes/messages.$id'
import { Route as BrandSavedRouteImport } from './routes/brand.saved'
import { Route as BrandProposalsRouteImport } from './routes/brand.proposals'
import { Route as BrandOnboardingRouteImport } from './routes/brand.onboarding'
import { Route as BrandMatchesRouteImport } from './routes/brand.matches'
import { Route as BrandDashboardRouteImport } from './routes/brand.dashboard'
import { Route as AthleteOpportunitiesRouteImport } from './routes/athlete.opportunities'
import { Route as AthleteOnboardingRouteImport } from './routes/athlete.onboarding'
import { Route as AthleteDashboardRouteImport } from './routes/athlete.dashboard'
import { Route as AthleteContractsRouteImport } from './routes/athlete.contracts'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as BrandCampaignsNewRouteImport } from './routes/brand.campaigns.new'
import { Route as BrandCampaignsIdRouteImport } from './routes/brand.campaigns.$id'
import { Route as BrandAthletesIdRouteImport } from './routes/brand.athletes.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIdRoute = MessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MessagesRoute,
} as any)
const BrandSavedRoute = BrandSavedRouteImport.update({
  id: '/brand/saved',
  path: '/brand/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandProposalsRoute = BrandProposalsRouteImport.update({
  id: '/brand/proposals',
  path: '/brand/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandOnboardingRoute = BrandOnboardingRouteImport.update({
  id: '/brand/onboarding',
  path: '/brand/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandMatchesRoute = BrandMatchesRouteImport.update({
  id: '/brand/matches',
  path: '/brand/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandDashboardRoute = BrandDashboardRouteImport.update({
  id: '/brand/dashboard',
  path: '/brand/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteOpportunitiesRoute = AthleteOpportunitiesRouteImport.update({
  id: '/athlete/opportunities',
  path: '/athlete/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteOnboardingRoute = AthleteOnboardingRouteImport.update({
  id: '/athlete/onboarding',
  path: '/athlete/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteDashboardRoute = AthleteDashboardRouteImport.update({
  id: '/athlete/dashboard',
  path: '/athlete/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteContractsRoute = AthleteContractsRouteImport.update({
  id: '/athlete/contracts',
  path: '/athlete/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandCampaignsNewRoute = BrandCampaignsNewRouteImport.update({
  id: '/brand/campaigns/new',
  path: '/brand/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandCampaignsIdRoute = BrandCampaignsIdRouteImport.update({
  id: '/brand/campaigns/$id',
  path: '/brand/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandAthletesIdRoute = BrandAthletesIdRouteImport.update({
  id: '/brand/athletes/$id',
  path: '/brand/athletes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/messages': typeof MessagesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/athlete/contracts': typeof AthleteContractsRoute
  '/athlete/dashboard': typeof AthleteDashboardRoute
  '/athlete/onboarding': typeof AthleteOnboardingRoute
  '/athlete/opportunities': typeof AthleteOpportunitiesRoute
  '/brand/dashboard': typeof BrandDashboardRoute
  '/brand/matches': typeof BrandMatchesRoute
  '/brand/onboarding': typeof BrandOnboardingRoute
  '/brand/proposals': typeof BrandProposalsRoute
  '/brand/saved': typeof BrandSavedRoute
  '/messages/$id': typeof MessagesIdRoute
  '/brand/athletes/$id': typeof BrandAthletesIdRoute
  '/brand/campaigns/$id': typeof BrandCampaignsIdRoute
  '/brand/campaigns/new': typeof BrandCampaignsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/messages': typeof MessagesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/athlete/contracts': typeof AthleteContractsRoute
  '/athlete/dashboard': typeof AthleteDashboardRoute
  '/athlete/onboarding': typeof AthleteOnboardingRoute
  '/athlete/opportunities': typeof AthleteOpportunitiesRoute
  '/brand/dashboard': typeof BrandDashboardRoute
  '/brand/matches': typeof BrandMatchesRoute
  '/brand/onboarding': typeof BrandOnboardingRoute
  '/brand/proposals': typeof BrandProposalsRoute
  '/brand/saved': typeof BrandSavedRoute
  '/messages/$id': typeof MessagesIdRoute
  '/brand/athletes/$id': typeof BrandAthletesIdRoute
  '/brand/campaigns/$id': typeof BrandCampaignsIdRoute
  '/brand/campaigns/new': typeof BrandCampaignsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/messages': typeof MessagesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/athlete/contracts': typeof AthleteContractsRoute
  '/athlete/dashboard': typeof AthleteDashboardRoute
  '/athlete/onboarding': typeof AthleteOnboardingRoute
  '/athlete/opportunities': typeof AthleteOpportunitiesRoute
  '/brand/dashboard': typeof BrandDashboardRoute
  '/brand/matches': typeof BrandMatchesRoute
  '/brand/onboarding': typeof BrandOnboardingRoute
  '/brand/proposals': typeof BrandProposalsRoute
  '/brand/saved': typeof BrandSavedRoute
  '/messages/$id': typeof MessagesIdRoute
  '/brand/athletes/$id': typeof BrandAthletesIdRoute
  '/brand/campaigns/$id': typeof BrandCampaignsIdRoute
  '/brand/campaigns/new': typeof BrandCampaignsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/messages'
    | '/reset-password'
    | '/admin/dashboard'
    | '/athlete/contracts'
    | '/athlete/dashboard'
    | '/athlete/onboarding'
    | '/athlete/opportunities'
    | '/brand/dashboard'
    | '/brand/matches'
    | '/brand/onboarding'
    | '/brand/proposals'
    | '/brand/saved'
    | '/messages/$id'
    | '/brand/athletes/$id'
    | '/brand/campaigns/$id'
    | '/brand/campaigns/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/messages'
    | '/reset-password'
    | '/admin/dashboard'
    | '/athlete/contracts'
    | '/athlete/dashboard'
    | '/athlete/onboarding'
    | '/athlete/opportunities'
    | '/brand/dashboard'
    | '/brand/matches'
    | '/brand/onboarding'
    | '/brand/proposals'
    | '/brand/saved'
    | '/messages/$id'
    | '/brand/athletes/$id'
    | '/brand/campaigns/$id'
    | '/brand/campaigns/new'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/messages'
    | '/reset-password'
    | '/admin/dashboard'
    | '/athlete/contracts'
    | '/athlete/dashboard'
    | '/athlete/onboarding'
    | '/athlete/opportunities'
    | '/brand/dashboard'
    | '/brand/matches'
    | '/brand/onboarding'
    | '/brand/proposals'
    | '/brand/saved'
    | '/messages/$id'
    | '/brand/athletes/$id'
    | '/brand/campaigns/$id'
    | '/brand/campaigns/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AthleteContractsRoute: typeof AthleteContractsRoute
  AthleteDashboardRoute: typeof AthleteDashboardRoute
  AthleteOnboardingRoute: typeof AthleteOnboardingRoute
  AthleteOpportunitiesRoute: typeof AthleteOpportunitiesRoute
  BrandDashboardRoute: typeof BrandDashboardRoute
  BrandMatchesRoute: typeof BrandMatchesRoute
  BrandOnboardingRoute: typeof BrandOnboardingRoute
  BrandProposalsRoute: typeof BrandProposalsRoute
  BrandSavedRoute: typeof BrandSavedRoute
  BrandAthletesIdRoute: typeof BrandAthletesIdRoute
  BrandCampaignsIdRoute: typeof BrandCampaignsIdRoute
  BrandCampaignsNewRoute: typeof BrandCampaignsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$id': {
      id: '/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof MessagesIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/brand/saved': {
      id: '/brand/saved'
      path: '/brand/saved'
      fullPath: '/brand/saved'
      preLoaderRoute: typeof BrandSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/proposals': {
      id: '/brand/proposals'
      path: '/brand/proposals'
      fullPath: '/brand/proposals'
      preLoaderRoute: typeof BrandProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/onboarding': {
      id: '/brand/onboarding'
      path: '/brand/onboarding'
      fullPath: '/brand/onboarding'
      preLoaderRoute: typeof BrandOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/matches': {
      id: '/brand/matches'
      path: '/brand/matches'
      fullPath: '/brand/matches'
      preLoaderRoute: typeof BrandMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/dashboard': {
      id: '/brand/dashboard'
      path: '/brand/dashboard'
      fullPath: '/brand/dashboard'
      preLoaderRoute: typeof BrandDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/opportunities': {
      id: '/athlete/opportunities'
      path: '/athlete/opportunities'
      fullPath: '/athlete/opportunities'
      preLoaderRoute: typeof AthleteOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/onboarding': {
      id: '/athlete/onboarding'
      path: '/athlete/onboarding'
      fullPath: '/athlete/onboarding'
      preLoaderRoute: typeof AthleteOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/dashboard': {
      id: '/athlete/dashboard'
      path: '/athlete/dashboard'
      fullPath: '/athlete/dashboard'
      preLoaderRoute: typeof AthleteDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/contracts': {
      id: '/athlete/contracts'
      path: '/athlete/contracts'
      fullPath: '/athlete/contracts'
      preLoaderRoute: typeof AthleteContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/campaigns/new': {
      id: '/brand/campaigns/new'
      path: '/brand/campaigns/new'
      fullPath: '/brand/campaigns/new'
      preLoaderRoute: typeof BrandCampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/campaigns/$id': {
      id: '/brand/campaigns/$id'
      path: '/brand/campaigns/$id'
      fullPath: '/brand/campaigns/$id'
      preLoaderRoute: typeof BrandCampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/athletes/$id': {
      id: '/brand/athletes/$id'
      path: '/brand/athletes/$id'
      fullPath: '/brand/athletes/$id'
      preLoaderRoute: typeof BrandAthletesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MessagesRouteChildren {
  MessagesIdRoute: typeof MessagesIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesIdRoute: MessagesIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  MessagesRoute: MessagesRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AthleteContractsRoute: AthleteContractsRoute,
  AthleteDashboardRoute: AthleteDashboardRoute,
  AthleteOnboardingRoute: AthleteOnboardingRoute,
  AthleteOpportunitiesRoute: AthleteOpportunitiesRoute,
  BrandDashboardRoute: BrandDashboardRoute,
  BrandMatchesRoute: BrandMatchesRoute,
  BrandOnboardingRoute: BrandOnboardingRoute,
  BrandProposalsRoute: BrandProposalsRoute,
  BrandSavedRoute: BrandSavedRoute,
  BrandAthletesIdRoute: BrandAthletesIdRoute,
  BrandCampaignsIdRoute: BrandCampaignsIdRoute,
  BrandCampaignsNewRoute: BrandCampaignsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
