/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesIdRouteImport } from './routes/messages.$id'
import { Route as DisputesNewRouteImport } from './routes/disputes.new'
import { Route as ContractsIdRouteImport } from './routes/contracts.$id'
import { Route as BrandSavedRouteImport } from './routes/brand.saved'
import { Route as BrandProposalsRouteImport } from './routes/brand.proposals'
import { Route as BrandPipelineRouteImport } from './routes/brand.pipeline'
import { Route as BrandOnboardingRouteImport } from './routes/brand.onboarding'
import { Route as BrandMatchesRouteImport } from './routes/brand.matches'
import { Route as BrandDashboardRouteImport } from './routes/brand.dashboard'
import { Route as BrandContractsRouteImport } from './routes/brand.contracts'
import { Route as AthletePricingRouteImport } from './routes/athlete.pricing'
import { Route as AthleteOpportunitiesRouteImport } from './routes/athlete.opportunities'
import { Route as AthleteOnboardingRouteImport } from './routes/athlete.onboarding'
import { Route as AthleteFeedRouteImport } from './routes/athlete.feed'
import { Route as AthleteEarningsRouteImport } from './routes/athlete.earnings'
import { Route as AthleteDealsRouteImport } from './routes/athlete.deals'
import { Route as AthleteDashboardRouteImport } from './routes/athlete.dashboard'
import { Route as AthleteContractsRouteImport } from './routes/athlete.contracts'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminContractsRouteImport } from './routes/admin.contracts'
import { Route as BrandCampaignsNewRouteImport } from './routes/brand.campaigns.new'
import { Route as BrandCampaignsIdRouteImport } from './routes/brand.campaigns.$id'
import { Route as BrandAthletesIdRouteImport } from './routes/brand.athletes.$id'
import { Route as BrandCampaignsIdLaunchedRouteImport } from './routes/brand.campaigns.$id.launched'

const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIdRoute = MessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MessagesRoute,
} as any)
const DisputesNewRoute = DisputesNewRouteImport.update({
  id: '/disputes/new',
  path: '/disputes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsIdRoute = ContractsIdRouteImport.update({
  id: '/contracts/$id',
  path: '/contracts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandSavedRoute = BrandSavedRouteImport.update({
  id: '/brand/saved',
  path: '/brand/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandProposalsRoute = BrandProposalsRouteImport.update({
  id: '/brand/proposals',
  path: '/brand/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandPipelineRoute = BrandPipelineRouteImport.update({
  id: '/brand/pipeline',
  path: '/brand/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandOnboardingRoute = BrandOnboardingRouteImport.update({
  id: '/brand/onboarding',
  path: '/brand/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandMatchesRoute = BrandMatchesRouteImport.update({
  id: '/brand/matches',
  path: '/brand/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandDashboardRoute = BrandDashboardRouteImport.update({
  id: '/brand/dashboard',
  path: '/brand/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandContractsRoute = BrandContractsRouteImport.update({
  id: '/brand/contracts',
  path: '/brand/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletePricingRoute = AthletePricingRouteImport.update({
  id: '/athlete/pricing',
  path: '/athlete/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteOpportunitiesRoute = AthleteOpportunitiesRouteImport.update({
  id: '/athlete/opportunities',
  path: '/athlete/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteOnboardingRoute = AthleteOnboardingRouteImport.update({
  id: '/athlete/onboarding',
  path: '/athlete/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteFeedRoute = AthleteFeedRouteImport.update({
  id: '/athlete/feed',
  path: '/athlete/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteEarningsRoute = AthleteEarningsRouteImport.update({
  id: '/athlete/earnings',
  path: '/athlete/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteDealsRoute = AthleteDealsRouteImport.update({
  id: '/athlete/deals',
  path: '/athlete/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteDashboardRoute = AthleteDashboardRouteImport.update({
  id: '/athlete/dashboard',
  path: '/athlete/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteContractsRoute = AthleteContractsRouteImport.update({
  id: '/athlete/contracts',
  path: '/athlete/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/admin/revenue',
  path: '/admin/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/admin/disputes',
  path: '/admin/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContractsRoute = AdminContractsRouteImport.update({
  id: '/admin/contracts',
  path: '/admin/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandCampaignsNewRoute = BrandCampaignsNewRouteImport.update({
  id: '/brand/campaigns/new',
  path: '/brand/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandCampaignsIdRoute = BrandCampaignsIdRouteImport.update({
  id: '/brand/campaigns/$id',
  path: '/brand/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandAthletesIdRoute = BrandAthletesIdRouteImport.update({
  id: '/brand/athletes/$id',
  path: '/brand/athletes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandCampaignsIdLaunchedRoute =
  BrandCampaignsIdLaunchedRouteImport.update({
    id: '/launched',
    path: '/launched',
    getParentRoute: () => BrandCampaignsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/messages': typeof MessagesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/subscription': typeof SubscriptionRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/athlete/contracts': typeof AthleteContractsRoute
  '/athlete/dashboard': typeof AthleteDashboardRoute
  '/athlete/deals': typeof AthleteDealsRoute
  '/athlete/earnings': typeof AthleteEarningsRoute
  '/athlete/feed': typeof AthleteFeedRoute
  '/athlete/onboarding': typeof AthleteOnboardingRoute
  '/athlete/opportunities': typeof AthleteOpportunitiesRoute
  '/athlete/pricing': typeof AthletePricingRoute
  '/brand/contracts': typeof BrandContractsRoute
  '/brand/dashboard': typeof BrandDashboardRoute
  '/brand/matches': typeof BrandMatchesRoute
  '/brand/onboarding': typeof BrandOnboardingRoute
  '/brand/pipeline': typeof BrandPipelineRoute
  '/brand/proposals': typeof BrandProposalsRoute
  '/brand/saved': typeof BrandSavedRoute
  '/contracts/$id': typeof ContractsIdRoute
  '/disputes/new': typeof DisputesNewRoute
  '/messages/$id': typeof MessagesIdRoute
  '/brand/athletes/$id': typeof BrandAthletesIdRoute
  '/brand/campaigns/$id': typeof BrandCampaignsIdRouteWithChildren
  '/brand/campaigns/new': typeof BrandCampaignsNewRoute
  '/brand/campaigns/$id/launched': typeof BrandCampaignsIdLaunchedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/messages': typeof MessagesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/subscription': typeof SubscriptionRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/athlete/contracts': typeof AthleteContractsRoute
  '/athlete/dashboard': typeof AthleteDashboardRoute
  '/athlete/deals': typeof AthleteDealsRoute
  '/athlete/earnings': typeof AthleteEarningsRoute
  '/athlete/feed': typeof AthleteFeedRoute
  '/athlete/onboarding': typeof AthleteOnboardingRoute
  '/athlete/opportunities': typeof AthleteOpportunitiesRoute
  '/athlete/pricing': typeof AthletePricingRoute
  '/brand/contracts': typeof BrandContractsRoute
  '/brand/dashboard': typeof BrandDashboardRoute
  '/brand/matches': typeof BrandMatchesRoute
  '/brand/onboarding': typeof BrandOnboardingRoute
  '/brand/pipeline': typeof BrandPipelineRoute
  '/brand/proposals': typeof BrandProposalsRoute
  '/brand/saved': typeof BrandSavedRoute
  '/contracts/$id': typeof ContractsIdRoute
  '/disputes/new': typeof DisputesNewRoute
  '/messages/$id': typeof MessagesIdRoute
  '/brand/athletes/$id': typeof BrandAthletesIdRoute
  '/brand/campaigns/$id': typeof BrandCampaignsIdRouteWithChildren
  '/brand/campaigns/new': typeof BrandCampaignsNewRoute
  '/brand/campaigns/$id/launched': typeof BrandCampaignsIdLaunchedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/messages': typeof MessagesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/subscription': typeof SubscriptionRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/athlete/contracts': typeof AthleteContractsRoute
  '/athlete/dashboard': typeof AthleteDashboardRoute
  '/athlete/deals': typeof AthleteDealsRoute
  '/athlete/earnings': typeof AthleteEarningsRoute
  '/athlete/feed': typeof AthleteFeedRoute
  '/athlete/onboarding': typeof AthleteOnboardingRoute
  '/athlete/opportunities': typeof AthleteOpportunitiesRoute
  '/athlete/pricing': typeof AthletePricingRoute
  '/brand/contracts': typeof BrandContractsRoute
  '/brand/dashboard': typeof BrandDashboardRoute
  '/brand/matches': typeof BrandMatchesRoute
  '/brand/onboarding': typeof BrandOnboardingRoute
  '/brand/pipeline': typeof BrandPipelineRoute
  '/brand/proposals': typeof BrandProposalsRoute
  '/brand/saved': typeof BrandSavedRoute
  '/contracts/$id': typeof ContractsIdRoute
  '/disputes/new': typeof DisputesNewRoute
  '/messages/$id': typeof MessagesIdRoute
  '/brand/athletes/$id': typeof BrandAthletesIdRoute
  '/brand/campaigns/$id': typeof BrandCampaignsIdRouteWithChildren
  '/brand/campaigns/new': typeof BrandCampaignsNewRoute
  '/brand/campaigns/$id/launched': typeof BrandCampaignsIdLaunchedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/demo'
    | '/forgot-password'
    | '/messages'
    | '/reset-password'
    | '/subscription'
    | '/admin/contracts'
    | '/admin/dashboard'
    | '/admin/disputes'
    | '/admin/revenue'
    | '/athlete/contracts'
    | '/athlete/dashboard'
    | '/athlete/deals'
    | '/athlete/earnings'
    | '/athlete/feed'
    | '/athlete/onboarding'
    | '/athlete/opportunities'
    | '/athlete/pricing'
    | '/brand/contracts'
    | '/brand/dashboard'
    | '/brand/matches'
    | '/brand/onboarding'
    | '/brand/pipeline'
    | '/brand/proposals'
    | '/brand/saved'
    | '/contracts/$id'
    | '/disputes/new'
    | '/messages/$id'
    | '/brand/athletes/$id'
    | '/brand/campaigns/$id'
    | '/brand/campaigns/new'
    | '/brand/campaigns/$id/launched'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/demo'
    | '/forgot-password'
    | '/messages'
    | '/reset-password'
    | '/subscription'
    | '/admin/contracts'
    | '/admin/dashboard'
    | '/admin/disputes'
    | '/admin/revenue'
    | '/athlete/contracts'
    | '/athlete/dashboard'
    | '/athlete/deals'
    | '/athlete/earnings'
    | '/athlete/feed'
    | '/athlete/onboarding'
    | '/athlete/opportunities'
    | '/athlete/pricing'
    | '/brand/contracts'
    | '/brand/dashboard'
    | '/brand/matches'
    | '/brand/onboarding'
    | '/brand/pipeline'
    | '/brand/proposals'
    | '/brand/saved'
    | '/contracts/$id'
    | '/disputes/new'
    | '/messages/$id'
    | '/brand/athletes/$id'
    | '/brand/campaigns/$id'
    | '/brand/campaigns/new'
    | '/brand/campaigns/$id/launched'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/demo'
    | '/forgot-password'
    | '/messages'
    | '/reset-password'
    | '/subscription'
    | '/admin/contracts'
    | '/admin/dashboard'
    | '/admin/disputes'
    | '/admin/revenue'
    | '/athlete/contracts'
    | '/athlete/dashboard'
    | '/athlete/deals'
    | '/athlete/earnings'
    | '/athlete/feed'
    | '/athlete/onboarding'
    | '/athlete/opportunities'
    | '/athlete/pricing'
    | '/brand/contracts'
    | '/brand/dashboard'
    | '/brand/matches'
    | '/brand/onboarding'
    | '/brand/pipeline'
    | '/brand/proposals'
    | '/brand/saved'
    | '/contracts/$id'
    | '/disputes/new'
    | '/messages/$id'
    | '/brand/athletes/$id'
    | '/brand/campaigns/$id'
    | '/brand/campaigns/new'
    | '/brand/campaigns/$id/launched'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SubscriptionRoute: typeof SubscriptionRoute
  AdminContractsRoute: typeof AdminContractsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AthleteContractsRoute: typeof AthleteContractsRoute
  AthleteDashboardRoute: typeof AthleteDashboardRoute
  AthleteDealsRoute: typeof AthleteDealsRoute
  AthleteEarningsRoute: typeof AthleteEarningsRoute
  AthleteFeedRoute: typeof AthleteFeedRoute
  AthleteOnboardingRoute: typeof AthleteOnboardingRoute
  AthleteOpportunitiesRoute: typeof AthleteOpportunitiesRoute
  AthletePricingRoute: typeof AthletePricingRoute
  BrandContractsRoute: typeof BrandContractsRoute
  BrandDashboardRoute: typeof BrandDashboardRoute
  BrandMatchesRoute: typeof BrandMatchesRoute
  BrandOnboardingRoute: typeof BrandOnboardingRoute
  BrandPipelineRoute: typeof BrandPipelineRoute
  BrandProposalsRoute: typeof BrandProposalsRoute
  BrandSavedRoute: typeof BrandSavedRoute
  ContractsIdRoute: typeof ContractsIdRoute
  DisputesNewRoute: typeof DisputesNewRoute
  BrandAthletesIdRoute: typeof BrandAthletesIdRoute
  BrandCampaignsIdRoute: typeof BrandCampaignsIdRouteWithChildren
  BrandCampaignsNewRoute: typeof BrandCampaignsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$id': {
      id: '/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof MessagesIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/disputes/new': {
      id: '/disputes/new'
      path: '/disputes/new'
      fullPath: '/disputes/new'
      preLoaderRoute: typeof DisputesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/$id': {
      id: '/contracts/$id'
      path: '/contracts/$id'
      fullPath: '/contracts/$id'
      preLoaderRoute: typeof ContractsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/saved': {
      id: '/brand/saved'
      path: '/brand/saved'
      fullPath: '/brand/saved'
      preLoaderRoute: typeof BrandSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/proposals': {
      id: '/brand/proposals'
      path: '/brand/proposals'
      fullPath: '/brand/proposals'
      preLoaderRoute: typeof BrandProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/pipeline': {
      id: '/brand/pipeline'
      path: '/brand/pipeline'
      fullPath: '/brand/pipeline'
      preLoaderRoute: typeof BrandPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/onboarding': {
      id: '/brand/onboarding'
      path: '/brand/onboarding'
      fullPath: '/brand/onboarding'
      preLoaderRoute: typeof BrandOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/matches': {
      id: '/brand/matches'
      path: '/brand/matches'
      fullPath: '/brand/matches'
      preLoaderRoute: typeof BrandMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/dashboard': {
      id: '/brand/dashboard'
      path: '/brand/dashboard'
      fullPath: '/brand/dashboard'
      preLoaderRoute: typeof BrandDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/contracts': {
      id: '/brand/contracts'
      path: '/brand/contracts'
      fullPath: '/brand/contracts'
      preLoaderRoute: typeof BrandContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/pricing': {
      id: '/athlete/pricing'
      path: '/athlete/pricing'
      fullPath: '/athlete/pricing'
      preLoaderRoute: typeof AthletePricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/opportunities': {
      id: '/athlete/opportunities'
      path: '/athlete/opportunities'
      fullPath: '/athlete/opportunities'
      preLoaderRoute: typeof AthleteOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/onboarding': {
      id: '/athlete/onboarding'
      path: '/athlete/onboarding'
      fullPath: '/athlete/onboarding'
      preLoaderRoute: typeof AthleteOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/feed': {
      id: '/athlete/feed'
      path: '/athlete/feed'
      fullPath: '/athlete/feed'
      preLoaderRoute: typeof AthleteFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/earnings': {
      id: '/athlete/earnings'
      path: '/athlete/earnings'
      fullPath: '/athlete/earnings'
      preLoaderRoute: typeof AthleteEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/deals': {
      id: '/athlete/deals'
      path: '/athlete/deals'
      fullPath: '/athlete/deals'
      preLoaderRoute: typeof AthleteDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/dashboard': {
      id: '/athlete/dashboard'
      path: '/athlete/dashboard'
      fullPath: '/athlete/dashboard'
      preLoaderRoute: typeof AthleteDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/contracts': {
      id: '/athlete/contracts'
      path: '/athlete/contracts'
      fullPath: '/athlete/contracts'
      preLoaderRoute: typeof AthleteContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/admin/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/admin/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contracts': {
      id: '/admin/contracts'
      path: '/admin/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AdminContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/campaigns/new': {
      id: '/brand/campaigns/new'
      path: '/brand/campaigns/new'
      fullPath: '/brand/campaigns/new'
      preLoaderRoute: typeof BrandCampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/campaigns/$id': {
      id: '/brand/campaigns/$id'
      path: '/brand/campaigns/$id'
      fullPath: '/brand/campaigns/$id'
      preLoaderRoute: typeof BrandCampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/athletes/$id': {
      id: '/brand/athletes/$id'
      path: '/brand/athletes/$id'
      fullPath: '/brand/athletes/$id'
      preLoaderRoute: typeof BrandAthletesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/campaigns/$id/launched': {
      id: '/brand/campaigns/$id/launched'
      path: '/launched'
      fullPath: '/brand/campaigns/$id/launched'
      preLoaderRoute: typeof BrandCampaignsIdLaunchedRouteImport
      parentRoute: typeof BrandCampaignsIdRoute
    }
  }
}

interface MessagesRouteChildren {
  MessagesIdRoute: typeof MessagesIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesIdRoute: MessagesIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

interface BrandCampaignsIdRouteChildren {
  BrandCampaignsIdLaunchedRoute: typeof BrandCampaignsIdLaunchedRoute
}

const BrandCampaignsIdRouteChildren: BrandCampaignsIdRouteChildren = {
  BrandCampaignsIdLaunchedRoute: BrandCampaignsIdLaunchedRoute,
}

const BrandCampaignsIdRouteWithChildren =
  BrandCampaignsIdRoute._addFileChildren(BrandCampaignsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  MessagesRoute: MessagesRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SubscriptionRoute: SubscriptionRoute,
  AdminContractsRoute: AdminContractsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AthleteContractsRoute: AthleteContractsRoute,
  AthleteDashboardRoute: AthleteDashboardRoute,
  AthleteDealsRoute: AthleteDealsRoute,
  AthleteEarningsRoute: AthleteEarningsRoute,
  AthleteFeedRoute: AthleteFeedRoute,
  AthleteOnboardingRoute: AthleteOnboardingRoute,
  AthleteOpportunitiesRoute: AthleteOpportunitiesRoute,
  AthletePricingRoute: AthletePricingRoute,
  BrandContractsRoute: BrandContractsRoute,
  BrandDashboardRoute: BrandDashboardRoute,
  BrandMatchesRoute: BrandMatchesRoute,
  BrandOnboardingRoute: BrandOnboardingRoute,
  BrandPipelineRoute: BrandPipelineRoute,
  BrandProposalsRoute: BrandProposalsRoute,
  BrandSavedRoute: BrandSavedRoute,
  ContractsIdRoute: ContractsIdRoute,
  DisputesNewRoute: DisputesNewRoute,
  BrandAthletesIdRoute: BrandAthletesIdRoute,
  BrandCampaignsIdRoute: BrandCampaignsIdRouteWithChildren,
  BrandCampaignsNewRoute: BrandCampaignsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
